version: '3.1'

services:
  reddit-clone-mysql:
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: spring-reddit-clone
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    restart: always
    ports:
      - "9000:8080"
